name: Build and Deploy
on: push
jobs: 
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install Dependencies
      run: npm i
      
    - name: Build
      run: npm run build
    
    - name: Export
      run: npm run export
    
    - name: Disable jekyll processing
      run: touch ./out/.nojekyll
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages
        folder: out
        # ssh-key: ${{ secrets.DEPLOY_KEY }}